const languages = {
  ge: {
    title: "ვებ გვერდი მალე განახლდება",
    smallTitle: "გამოწერე სიახლეები",
    mailText:
      "დაგვიტოვეთ თქვენი საკონტაქტო ელ-ფოსტა და პირველმა მიიღეთ ინფორმაცია სიახლეების შესახებ",
    placeText: "ელ-ფოსტა",
    sendBtnText: "გაგზავნა",
    completeText:
      "თქვენ წარმატებით გამოწერეთ არხი. გთხოვთ, შეამოწმოთ თქვენი ელ-ფოსტა",
    rejectText: "მითითებული ელ-ფოსტის ფორმატი არასწორია",
    blankedText: "გთხოვთ მიუთითოთ ელ-ფოსტა",
    appTitle: "გადმოწერეთ ჩვენი აპლიკაცია",
    appText: "იყავი მუდამ კავშირზე და ისარგებლე უამრავი სერვისით ერთ სივრცეში!",
    lightMode: "ღია",
    darkMode: "მუქი",
    contactTitle: "კონტაქტი",
    contactAddress: "საქართველო, თბილისი, 0131 დ.აღმაშენებლის ხეივანი 172ბ",
    contactTel: "+995 32 2 500-555",
    contactMail: "info@mp.ge",
    mapText: "როგორ მივიდე",
  },
  ru: {
    title: "Сайт скоро будет обновлен",
    smallTitle: "Подписаться на новости",
    mailText:
      "Оставьте нам свой контактный e-mail и получайте информацию о новостях первыми",
    placeText: "электронная почта",
    sendBtnText: "Отправить",
    completeText:
      "Вы успешно подписались на канал. Пожалуйста, проверьте свою электронную почту",
    rejectText: "Указанный формат электронной почты недействителен",
    blankedText: "Пожалуйста, введите свой адрес электронной почты",
    appTitle: "Загрузите наше приложение",
    appText:
      "Оставайтесь на связи и наслаждайтесь множеством услуг в одном пространстве!",
    lightMode: "светлый",
    darkMode: "темнота",
    contactTitle: "Контакт",
    contactAddress: "Грузия, Тбилиси, 0131 переулок Д. Агмашенебели 172б",
    contactTel: "+995 32 2 500-555",
    contactMail: "info@mp.ge",
    mapText: "Как я могу попасть",
  },
  en: {
    title: "The website will be updated soon",
    smallTitle: "Subscribe to news",
    mailText:
      "Leave us your contact email. Mail and be the first to receive information about news",
    placeText: "e-mail",
    sendBtnText: "send",
    completeText:
      "You have successfully subscribed to the channel. Please check your email",
    rejectText: "The specified email format is invalid",
    blankedText: "Please enter your e-mail address",
    appTitle: "Download our app",
    appText: "Stay connected and enjoy many services in one space!",
    lightMode: "Light",
    darkMode: "Dark",
    contactTitle: "Contact",
    contactAddress: "Georgia, Tbilisi, 0131 D. Agmashenebeli alley 172b",
    contactTel: "+995 32 2 500-555",
    contactMail: "info@mp.ge",
    mapText: "How I get there",
  },
};
